### PR TITLE
add unique index on person email

### PR DESCRIPTION
**Pull request by devalirizwan**

### CODE REVIEW

**Review by brentkearney — CHANGES_REQUESTED** [review]
In addition to adding this unique requirement, we also need to handle what happens when a user adds a participant that already has a record in the Person table. As-is, this will just cause a crash.

**Comment by brentkearney** [comment]
Currently we search for existing person records that match all of firstname, lastname, and email:

https://github.com/birs-math/proposals/blob/d5e4e40628869ac735f5ac4af866fc8e83f13b49/app/controllers/invites_controller.rb#L102

So if someone spells the first or last name slightly different, it will create a new record. We need to search on email only, as that is a person's unique identifier.

**Comment by devalirizwan** [comment]
@brentkearney - Added rake task that will remove duplicate records from person table. 

second comment has been resolved in this commit.
 https://github.com/birs-math/proposals/blob/251a3afe9e28a38a18ebd7e2b42514498c101a1a/app/models/invite.rb#L53

**Review by brentkearney — CHANGES_REQUESTED** [review]
The `InvitesController#add_person` method will cause an application crash when someone tries to invite John Smith (john@smith.edu) when Johnathan Smith (john@smith.edu) already exists.

https://github.com/birs-math/proposals/blob/d5e4e40628869ac735f5ac4af866fc8e83f13b49/app/controllers/invites_controller.rb#L102

I think this should fix it:

```
@invite.person = Person.find_by_email(@invite.email) || Person.create(firstname: @invite.firstname, lastname: @invite.lastname, email: @invite.email)
```

We should also add an rspec test for the above scenario, to ensure that duplicate Person records are properly handled.

**Comment by brentkearney** [comment]
[Bug: email addresses should be unique in the Person table](https://trello.com/c/8rzQbZh8/271-bug-email-addresses-should-be-unique-in-the-person-table)

**Review by brentkearney — APPROVED** [review]

**Pull request merged**
