### PR TITLE
Added 'edit faq page' feature

### PR DESCRIPTION
**Pull request by devalirizwan**

### CODE REVIEW

**Review by brentkearney — CHANGES_REQUESTED** [review]
Tests fail with the error:

```
Failure/Error: //= require trix/dist/trix
      
      ActionView::Template::Error:
        couldn't find file 'trix/dist/trix' with type 'text/css'
```

Is there a file that needs to be added to the commit, or a command that needs to be run to install Trix? An addition to the Gemfile?

**Comment by devalirizwan** [comment]
@brentkearney - yes this is the command to install trix. `bin/rails action_text:install` 

https://guides.rubyonrails.org/action_text_overview.html

**Comment by brentkearney** [comment]
> @brentkearney - yes this is the command to install trix. `bin/rails action_text:install`
> 
> https://guides.rubyonrails.org/action_text_overview.html

Great, thanks -- will add this to the Docker entrypoint script.

**Review by brentkearney — CHANGES_REQUESTED** [review]
Please update the code style issues identified at:

https://app.codacy.com/gh/birs-math/proposals/pullRequest?prid=7747048#newIssuesView

This are mostly replacing tabs with spaces, and other minor tweaks. Thanks

**Comment by brentkearney** [comment]
[As a staff member, I want to edit the FAQ page so that I can update the information on the page](https://trello.com/c/lisVUyJR/261-as-a-staff-member-i-want-to-edit-the-faq-page-so-that-i-can-update-the-information-on-the-page)

**Comment by devalirizwan** [comment]
> > @brentkearney - yes this is the command to install trix. `bin/rails action_text:install`
> > https://guides.rubyonrails.org/action_text_overview.html
> 
> Great, thanks -- will add this to the Docker entrypoint script.

@brentkearney - code syle issues resolved please add this command to the script so all checks get passed. Thanks.

**Review by brentkearney — APPROVED** [review]

**Pull request merged**
